version: 0.2

env:
  variables:
    GRADLE_OPTS: -Xmx1024m

phases:
  install:
    runtime-versions:
      docker: 18
      java: openjdk11

    commands:
      - echo [PHASE] Entered the install phase...
      - docker ps
      - pip --no-cache-dir install awscli
      - aws --version
      - aws sts get-caller-identity --query Account --output text
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - set
      - set | grep CODEBUILD

  build:
    commands:
      - echo [PHASE] Entered the build phase...
      - export BUILD_VERSION=${CODEBUILD_START_TIME}
      - make cibuild

  post_build:
    commands:
      - echo [PHASE] Entered the post_build phase...
      - make cipublish

artifacts:
  files:
    - 'ecs/*'
  name: simpleportal-$(BUILD_VERSION)